/* Auto-generated by cbindgen — do not edit. Regenerate via `cargo xtask vendor-header`. */

#ifndef BMU_CORE_H
#define BMU_CORE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Nombre maximum de batteries supporté (miroir de `bmu_types::MAX_BATTERIES`).
 *
 * **Littéral explicite obligatoire** pour que `cbindgen` émette un
 * `#define MAX_BATTERIES 16` dans `bmu_core.h` — il n'évalue pas les
 * expressions const (il ne suivrait pas `= bmu_types::MAX_BATTERIES`).
 * Une assertion statique vérifie la cohérence avec la source authoritative.
 */
#define MAX_BATTERIES 16

/**
 * Codes de retour C-friendly exposés par la façade `extern "C"`.
 */
#define BMU_OK 0

#define BMU_ERR_NULL -1

#define BMU_ERR_INVALID_CONFIG -2

#define BMU_ERR_INVALID_INDEX -3

#define BMU_ERR_BUSY -4

#define BMU_ERR_UNSUPPORTED -5

/**
 * Instance core — possédée par l'appelant C via pointeur opaque `BmuCore*`.
 *
 * Agrège la configuration, le `BatteryManager` (counters + `Ah`), le
 * `RintEngine` (mesure `R_int`), le `BalancerEngine` (`PWM` duty), le
 * dernier `Snapshot` produit et les `pending_latch` issus de commandes
 * `ForceOff`.
 *
 * NOTE : `Clone` uniquement (pas `Copy`) — les sous-composants sont
 * stateful, une copie silencieuse créerait une divergence.
 */
struct BmuCore;

/**
 * Mirror `C` de `Config`.
 */
struct BmuConfigC {
  uint32_t umin_mv;
  uint32_t umax_mv;
  int32_t imax_ma;
  uint32_t vdiff_imbalance_mv;
  uint8_t nb_switch_max;
  uint32_t reconnect_delay_ms;
  uint32_t tick_period_ms;
};

/**
 * Dump brut des registres `INA`/`TCA` lus par la couche C avant d'appeler `tick()`.
 */
struct BmuRawInputs {
  uint8_t n_ina;
  uint8_t n_tca;
  uint8_t ina_registers[16][18];
  uint8_t tca_inputs[4];
  int16_t climate_temp_c10;
  uint16_t climate_rh_pct10;
  uint64_t monotonic_us;
};

/**
 * Mirror `C` de `Battery`.
 */
struct BmuBatteryC {
  uint8_t idx;
  uint8_t state;
  uint8_t state_reason;
  uint8_t switch_count;
  int32_t voltage_mv;
  int32_t current_ma;
  int32_t ah_remaining_ma_h;
  int16_t temp_c10;
  uint8_t soh_pct;
  uint8_t balancer_duty_pct;
  uint32_t r_ohmic_m_ohms;
};

/**
 * Mirror `C` de `System`.
 */
struct BmuSystemC {
  uint8_t topology_ok;
  uint8_t n_bat;
  uint32_t tick_us_p50;
  uint32_t tick_us_p99;
  uint32_t wdt_feeds;
  uint64_t monotonic_us;
};

/**
 * Mirror `C` de `Snapshot`.
 */
struct BmuSnapshotC {
  uint8_t n_bat;
  struct BmuBatteryC batteries[MAX_BATTERIES];
  struct BmuSystemC system;
};

/**
 * Mirror `C` de `Actions` produites par `BmuCore::tick`.
 */
struct BmuActionsC {
  uint16_t tca_set_mask;
  uint16_t tca_clr_mask;
  uint8_t rint_trigger_idx;
  uint8_t request_soh_inference;
};

/**
 * Mirror `C` d'une commande entrante (`BLE`, `UI`, auto).
 */
struct BmuCommandC {
  /**
   * Discriminant : voir `BmuCommandKind` pour les valeurs valides.
   */
  uint8_t kind;
  uint8_t target_idx;
  /**
   * Payload interprété selon `kind` :
   * - `UpdateSoh` : `payload[0]` = `soh_pct`
   * - `SetConfig` : `payload[0..size_of::<BmuConfigC>()]` = `BmuConfigC` packed
   *   (vérification statique dans le test `setconfig_payload_fits`)
   * - `TopologyChanged` : `payload[0]` = `n_ina`, `payload[1]` = `n_tca`
   */
  uint8_t payload[32];
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Alloue un `BmuCore` et retourne un handle opaque. Retourne `NULL` si `cfg` est
 * `NULL` ou si la config échoue la validation.
 *
 * # Safety
 * Le caller doit appeler `bmu_core_destroy` exactement une fois pour libérer.
 * `cfg` doit pointer sur un `BmuConfigC` valide.
 *
 * **Exclusion mutuelle** : `BmuCore` n'est PAS protégé contre les accès
 * concurrents. Toutes les fonctions opérant sur un même handle (`tick`,
 * `command`, `get_cached_snapshot`, `set_config`, `serialize_battery`,
 * `destroy`) doivent être appelées depuis une seule tâche à la fois.
 * L'appelant est responsable de la synchronisation inter-tâches
 * (ex : `xSemaphoreTake` côté `ESP-IDF` avant chaque appel). La convention
 * KXKM est que seul `task_protection` possède le handle ; les autres
 * tâches (`task_ble`, `task_display`, `task_soh`) appellent exclusivement
 * `get_cached_snapshot` et `serialize_battery` derrière un mutex.
 */
struct BmuCore *bmu_core_init(const struct BmuConfigC *cfg);

/**
 * Libère un `BmuCore` alloué par `bmu_core_init`.
 *
 * # Safety
 * `core` doit être un pointeur retourné par `bmu_core_init`, non-`NULL`, et
 * non encore libéré. Après cet appel, le pointeur ne doit plus être utilisé.
 */
void bmu_core_destroy(struct BmuCore *core);

/**
 * Exécute un tick core : parse `BmuRawInputs`, appelle `step()`, écrit snapshot et actions.
 *
 * # Safety
 * `core`, `inputs`, `out_snapshot`, `out_actions` doivent être non-`NULL` et pointer
 * sur des objets valides et correctement alignés. `core` doit être un handle actif.
 */
int32_t bmu_core_tick(struct BmuCore *core,
                      const struct BmuRawInputs *inputs,
                      struct BmuSnapshotC *out_snapshot,
                      struct BmuActionsC *out_actions);

/**
 * Reçoit une commande depuis `BLE`/`UI`.
 *
 * # Safety
 * `core` et `cmd` doivent être non-`NULL` et valides.
 */
int32_t bmu_core_command(struct BmuCore *core, const struct BmuCommandC *cmd);

/**
 * Copie le dernier snapshot caché vers `out`. Utilisé par `task_ble` / `task_display` / `task_soh`.
 *
 * # Safety
 * `core` et `out` doivent être non-`NULL` et valides.
 */
int32_t bmu_core_get_cached_snapshot(const struct BmuCore *core,
                                     struct BmuSnapshotC *out);

/**
 * Applique une nouvelle config (avec validation bornes).
 *
 * # Safety
 * Les deux pointeurs doivent être valides et non-`NULL`.
 */
int32_t bmu_core_set_config(struct BmuCore *core, const struct BmuConfigC *cfg);

/**
 * Sérialise la batterie `idx` en 24 bytes packed big-endian pour la characteristic `BLE`.
 * Cf spec §7.2 layout.
 *
 * Layout : `[idx, state, reason, switch_count, voltage_mv_be32, current_ma_be32,
 * ah_remaining_be32, temp_c10_be16, soh_pct, balancer_duty_pct, r_ohmic_be32]`
 * = 1 + 1 + 1 + 1 + 4 + 4 + 4 + 2 + 1 + 1 + 4 = 24 bytes.
 *
 * # Safety
 * `core` doit être non-`NULL` et valide. `out_buf` doit pointer sur au moins
 * 24 bytes writable et correctement alignés pour `u8`.
 */
int32_t bmu_core_serialize_battery(const struct BmuCore *core, uint8_t idx, uint8_t *out_buf);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BMU_CORE_H */
