; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
build_type = debug
debug_tool = ftdi
debug_init_break = tbreak setup

; debug_init_cmds =
;    define pio_reset_halt_target
;    monitor reset halt
;    end
;   debug_init_break = tbreak setup
;  debug_server =
;    $PLATFORMIO_HOME_DIR/packages/tool-openocd-esp32/bin/openocd
;    -s $PLATFORMIO_HOME_DIR/packages/tool-openocd-esp32/share/openocd/scripts
;    -f interface/ftdi/esp32_devkitj_v1.cfg
;    -f board/esp-wrover-kit-3.3v.cfg
;    -c "program_esp32 {{build_path}}/{{firmware}} verify reset; shutdown"
;    -c "init; reset halt"
;    -c "exit"
;  debug_port = :3333
;  upload_port = /dev/ttyUSB0

upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder

build_flags =
    -fpermissive // Ajout pour éviter certaines erreurs de portée

[env]
; platform = espressif32
platform = https://github.com/platformio/platform-espressif32
; platform = https://github.com/platformio/platform-espressif32#v3.2.0  for KXKMSACIO < v99
framework = arduino
;board_build.f_cpu = 240000000L
;board_build.f_flash = 80000000L
;board_build.flash_mode = qio



lib_deps =
	; K32-core
	Wire
	https://github.com/adafruit/Adafruit_BusIO
	https://github.com/JChristensen/Timer
	https://github.com/josephlarralde/ArduinoEventEmitter
	SD
    EEPROM
	WiFi
	SPI
	Ethernet
	https://github.com/marian-craciunescu/ESP32Ping
	FS
    SPIFFS
	Arduino_JSON
	https://github.com/bblanchon/ArduinoJson.git
;	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/mobizt/ESP_SSLClient.git
	; https://github.com/KomplexKapharnaum/K32-lib
	
    ; https://github.com/Zanduino/INA.git
	; https://github.com/ftyers/INA/tree/ina237.git
	; https://github.com/ftyers/INA.git
 ;   https://github.com/karl-mohring/TCA95x5_driver.git
    https://github.com/RobTillaart/TCA9555.git
	;fabianober/WebSocketServer
	links2004/WebSockets
	NTPClient
    https://github.com/Links2004/arduinoWebSockets.git
	https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino.git
;	https://github.com/electron-rare/Debug-Logger.git
	
[env:kxkm-v3-16MB]
board = esp-wrover-kit
upload_speed = 512000
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
	${env.build_flags}
	-DHW_ENABLE_STM32=1
lib_deps =
	${env.lib_deps}
lib_extra_dirs =
	${env.lib_extra_dirs}

